#!/bin/zsh
# Engine-only package for macOS 12 (Monterey), where the app cannot run: llama-server with the AMD
# patches, built for macOS 12 and SSE4.2, its GPU libraries in Metal 2.4 without bf16, the chat page
# and a start script. The DMGs are not affected: this builds in its own directory.
#
# Run after ./scripts/build-engines.sh, which leaves vendor/llama.cpp patched.
#   ./scripts/make-engine-zip.sh [version]     -> dist/toshllm-engine-<version>-macos12-x86_64.zip
set -e
cd "$(dirname "$0")/.."
ROOT="$PWD"

VERSION="${1:-$(tr -d '[:space:]' < VERSION)}"
VERSION="${VERSION#v}"
NAME="toshllm-engine-$VERSION-macos12-x86_64"
LLAMA="vendor/llama.cpp"
BUILD="build-macos12"

[ -d "$LLAMA/ggml/src/ggml-metal" ] || { echo "run ./scripts/build-engines.sh first" >&2; exit 1; }
[ -f Assets/web-ui/index.html ] || { echo "Assets/web-ui is missing" >&2; exit 1; }

if [ -z "${DEVELOPER_DIR:-}" ] && [ -d /Applications/Xcode.app ]; then
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
fi
METAL="$(xcrun -f metal)"
METALLIB="$(xcrun -f metallib)"

cd "$LLAMA"
cmake -B "$BUILD" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DGGML_METAL=ON \
    -DGGML_METAL_EMBED_LIBRARY=ON \
    -DTOSH_ENABLE_DYNAMIC_MOE=ON \
    -DGGML_NATIVE=OFF \
    -DCMAKE_OSX_ARCHITECTURES=x86_64 \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
    -DCMAKE_CXX_FLAGS="-DTOSH_VERSION=$VERSION" \
    -DLLAMA_OPENSSL=OFF \
    -DGGML_SSE42=ON -DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF \
    -DGGML_F16C=OFF -DGGML_BMI2=OFF -DGGML_AVX_VNNI=OFF -DGGML_AVX512=OFF
cmake --build "$BUILD" --config Release -j "$(sysctl -n hw.ncpu)" -t llama-server test-backend-ops

# Monterey has no Metal 3 and no bf16 in its shader compiler
EMBED="$BUILD/ggml/src/ggml-metal/autogenerated"
KERNELS="$BUILD/bin/kernels"
rm -rf "$KERNELS"
mkdir -p "$KERNELS"
for src in $EMBED/ggml-metal-embed-*.metal; do
    name="${${src:t:r}#ggml-metal-embed-}"
    "$METAL" -O3 -mmacosx-version-min=12.0 -std=macos-metal2.4 \
        -DGGML_METAL_EMBED_LIBRARY \
        -I ggml/src -I ggml/src/ggml-metal \
        -c "$src" -o "$KERNELS/$name.air"
    "$METALLIB" "$KERNELS/$name.air" -o "$KERNELS/$name.metallib"
    # the engine loads a library only if its source matches the one embedded in the binary
    echo "$name $(shasum -a 256 "$src" | cut -d' ' -f1)" >> "$KERNELS/fingerprint"
done
rm -f "$KERNELS"/*.air
for bin in llama-server test-backend-ops; do
    minos="$(otool -l "$BUILD/bin/$bin" | awk '/minos/ {print $2; exit}')"
    [ "$minos" = "12.0" ] || { echo "$bin targets macOS $minos, not 12.0" >&2; exit 1; }
done
cd "$ROOT"

STAGE="dist/$NAME"
rm -rf "$STAGE" "dist/$NAME.zip"
mkdir -p "$STAGE/bin"
cp "$LLAMA/$BUILD/bin/llama-server" "$LLAMA/$BUILD/bin/test-backend-ops" "$STAGE/bin/"
cp -R "$LLAMA/$BUILD/bin/kernels" "$STAGE/bin/"
(cd Assets/web-ui && tar cf - .) | (mkdir -p "$ROOT/$STAGE/web-ui" && cd "$ROOT/$STAGE/web-ui" && tar xf -)
cp LICENSE "$STAGE/"

cat > "$STAGE/start.sh" <<'EOF'
#!/bin/sh
# Starts the ToshLLM engine with the settings the app applies on AMD GPUs.
# Usage: ./start.sh /path/to/model.gguf [extra llama-server arguments]
# Optional: CTX (context, default 8192), PORT (default 8080), NCMOE (MoE layers kept on the CPU).
set -e
cd "$(dirname "$0")"

if [ -z "$1" ] || [ ! -f "$1" ]; then
    echo "usage: ./start.sh /path/to/model.gguf [extra llama-server arguments]"
    exit 1
fi
MODEL="$1"
shift

# the AMD attention kernels are off unless asked for
export TOSH_FA_AMD=1

# with experts on the CPU, prefetching them keeps prompt reading on the GPU path
if [ -n "$NCMOE" ]; then
    export GGML_SCHED_PREFETCH_EXPERTS=1 GGML_CPU_NO_REPACK=1
    set -- --n-cpu-moe "$NCMOE" "$@"
fi

echo "Open http://127.0.0.1:${PORT:-8080} in your browser once the model has loaded."
exec ./bin/llama-server -m "$MODEL" -ngl 99 -c "${CTX:-8192}" -fa auto --load-mode none --jinja \
    --no-reasoning-preserve --cache-ram 2048 --host 127.0.0.1 --port "${PORT:-8080}" --path web-ui "$@"
EOF
chmod +x "$STAGE/start.sh"

cat > "$STAGE/README.txt" <<EOF
ToshLLM engine $VERSION for macOS 12 (Monterey)
===============================================

This is the inference engine of ToshLLM without the app: the same llama.cpp engine with the AMD
Metal patches that ships in ToshLLM $VERSION, built to run on macOS 12 and on CPUs without AVX
(SSE4.2 only). It serves a chat page in your browser instead of the ToshLLM window. On macOS 13
or newer, use the app instead.

Requirements: an Intel Mac on macOS 12 or newer with a Metal GPU.


1. Unzip it

   If macOS says the files cannot be opened, clear the download quarantine in Terminal, from the
   folder where you unzipped it:

       xattr -dr com.apple.quarantine $NAME


2. Optional: check the GPU kernels

   These commands compare the GPU against the CPU on thousands of small cases. Each takes a few
   minutes and prints a summary at the end:

       cd $NAME
       ./bin/test-backend-ops -b MTL0 -o MUL_MAT > mul_mat.txt 2>&1
       TOSH_FA_AMD=1 ./bin/test-backend-ops -b MTL0 -o FLASH_ATTN_EXT > flash_attn.txt 2>&1


3. Start it with a model

       ./start.sh ~/models/your-model.gguf

   When the log says "listening on http://127.0.0.1:8080", open http://127.0.0.1:8080 in your
   browser.

   Optional settings, placed before the command:

       CTX=16384 ./start.sh model.gguf     context length (default 8192)
       PORT=8081 ./start.sh model.gguf     another port
       NCMOE=20  ./start.sh model.gguf     keep the experts of the first 20 layers of a
                                           mixture-of-experts model in system RAM, for models
                                           larger than the memory of the card

   Any other llama-server option can be added after the model path.


Problems: https://github.com/engeldlgado/toshllm/issues (attach the files from step 2 and the
startup log, run with -lv 4 after the model path for more detail).

Source code: https://github.com/engeldlgado/toshllm (GPL-3.0, see LICENSE).
EOF

# SIGN_IDENTITY (CI): Developer ID with the hardened runtime, so the zip can be notarized
if [ -n "${SIGN_IDENTITY:-}" ]; then
    codesign --force --timestamp --options runtime -s "$SIGN_IDENTITY" "$STAGE/bin/llama-server" "$STAGE/bin/test-backend-ops"
fi
(cd dist && ditto -c -k --keepParent "$NAME" "$NAME.zip")
rm -rf "$STAGE"
echo "engine package ready: dist/$NAME.zip ($(du -h "dist/$NAME.zip" | cut -f1))"
