import XCTest
@testable import ToshLLM

/// The digest lookup behind the update check.
///
/// It used to take whichever line of `checksums.txt` merely *contained* the file's
/// name, which is a different file's digest whenever anything in the release
/// shares the prefix — and the failure then reads as tampering.
final class UpdateChecksumTests: XCTestCase {

    private let digestA = String(repeating: "a", count: 64)
    private let digestB = String(repeating: "b", count: 64)

    private var listing: String {
        """
        \(digestB)  ToshLLM.dmg.blockmap
        \(digestA)  ToshLLM.dmg
        \(digestB)  ToshLLM.dmg.sha256
        """
    }

    func testTheEntryForTheExactNameIsFound() {
        XCTAssertEqual(UpdateChecker.checksum(in: listing, for: "ToshLLM.dmg"), digestA)
    }

    /// The bug: the blockmap line sorts first, so a substring match returned its
    /// digest and every download failed verification as if it were corrupt.
    func testAFileWhoseNameIsAPrefixOfAnotherDoesNotBorrowItsDigest() {
        XCTAssertNil(UpdateChecker.checksum(in: listing, for: "ToshLLM"),
                     "a name that is only a prefix must not match anything")
        XCTAssertEqual(UpdateChecker.checksum(in: listing, for: "ToshLLM.dmg.sha256"), digestB)
    }

    func testTheOrderOfTheEntriesDoesNotMatter() {
        let reversed = """
        \(digestA)  ToshLLM.dmg
        \(digestB)  ToshLLM.dmg.blockmap
        """
        XCTAssertEqual(UpdateChecker.checksum(in: reversed, for: "ToshLLM.dmg"), digestA)
    }

    /// The three spellings `sha256sum` produces for the same file.
    func testTheThreeSpellingsOfANameAreAllAccepted() {
        let binary = """
        \(digestA) *ToshLLM.dmg
        \(digestB) *Other.dmg.blockmap
        """
        XCTAssertEqual(UpdateChecker.checksum(in: binary, for: "ToshLLM.dmg"), digestA)

        let dotted = """
        \(digestA)  ./ToshLLM.dmg
        \(digestB)  ./Other.dmg.blockmap
        """
        XCTAssertEqual(UpdateChecker.checksum(in: dotted, for: "ToshLLM.dmg"), digestA)
    }

    func testTabsSeparateTheFieldsToo() {
        XCTAssertEqual(UpdateChecker.checksum(in: "\(digestA)\tToshLLM.dmg", for: "ToshLLM.dmg"),
                       digestA)
    }

    func testAMissingEntryIsNilRatherThanSomeOtherFilesDigest() {
        XCTAssertNil(UpdateChecker.checksum(in: listing, for: "Other.dmg"))
        XCTAssertNil(UpdateChecker.checksum(in: "", for: "ToshLLM.dmg"))
        XCTAssertNil(UpdateChecker.checksum(in: digestA, for: "ToshLLM.dmg"),
                     "a line with no filename field is not an entry")
        XCTAssertNil(UpdateChecker.checksum(in: "# generated by the release job\n", for: "ToshLLM.dmg"))
    }
}